name: "Version uptick automation (shared)"

on:
  workflow_call:
    inputs:
        uptick_config:
          type: string
          required: true

jobs:
  uptick:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout ${{ github.ref }} branch in ${{ github.repository }} repository.
      uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

    - name: Download Kura version upticker tool
      uses: carlosperate/download-file-action@8b89cb8b4807765e7d63fe765cc600eb1919af11 # v1.1.2
      with:
        file-url: https://kura-repo.s3.us-west-2.amazonaws.com/esf_upticker_tool/version-uptick-0.1.0-linux-x86_64

    - name: Download desired upticker configuration file
      uses: carlosperate/download-file-action@8b89cb8b4807765e7d63fe765cc600eb1919af11 # v1.1.2
      with:
        file-url: https://raw.githubusercontent.com/eclipse-kura/.github/main/config/version_uptick/${{ inputs.uptick_config }}

    - name: Make the uptick tool executable
      run: |
        chmod +x ./version-uptick-0.1.0-linux-x86_64
      shell: bash

    - name: Run the uptick tool
      run: |
        ./version-uptick-0.1.0-linux-x86_64 \
        --commit --trace process-versions \
        --config-path ${{ inputs.uptick_config }} \
        --root-dir .
      shell: bash

    - name: Cleanup
      run: |
        rm ./version-uptick-0.1.0-linux-x86_64 \
        ${{ inputs.uptick_config }}
      shell: bash

    - name: Get version
      id: get-version
      run: "echo \"resolved-version=\
        $(mvn
          --file ./pom.xml
          -Dexec.executable=echo
          -Dexec.args='${project.version}'
          --quiet exec:exec --non-recursive
        )\" >> \"${GITHUB_OUTPUT}\""
      shell: bash

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54 # v4.2.4
      with:
        title: "chore: automated uptick to ${{ steps.get-version.outputs.resolved-version }}"
        commit-message: "chore: automated uptick to ${{ steps.get-version.outputs.resolved-version }}"
        body: |
          Automated changes by [_Version uptick automation_](https://github.com/eclipse-kura/.github/blob/main/.github/workflows/_shared-version-uptick.yml) action.
          - Automated uptick to ${{ steps.get-version.outputs.resolved-version }} version.
          - Automation ran using `${{ inputs.uptick_config }}` configuration.
        branch-suffix: timestamp
